//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajero
    {
        public int PasajeroId { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<bool> Tapabocas { get; set; }
        public Nullable<int> RutaBusId { get; set; }
        public Nullable<int> SillaAsignada { get; set; }
    
        public virtual RutaBus RutaBus { get; set; }
    }
}
