//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaBus
    {
        public int RutaBusId { get; set; }
        public Nullable<int> RutaId { get; set; }
        public Nullable<int> BusId { get; set; }
    
        public virtual Pasajero Pasajero { get; set; }
        public virtual Ruta Ruta { get; set; }
        public virtual Bus Bus { get; set; }
    }
}
