//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaBus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RutaBus()
        {
            this.Pasajero = new HashSet<Pasajero>();
        }
    
        public int RutaBusId { get; set; }
        public Nullable<int> RutaId { get; set; }
        public Nullable<int> BusId { get; set; }
    
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasajero> Pasajero { get; set; }
        public virtual Ruta Ruta { get; set; }
    }
}
